### PR TITLE
Update to RC3, use FileSource

### PR DESCRIPTION
**Pull request by ktoso**

### CODE REVIEW

**Comment by patriknw** [comment]
nothing in the tutorial text that needs update?
I think there are some links there, and it perhaps mention something about this file reading?

**Comment by ktoso** [comment]
Good point, I'll see what needs updating in the tutorial.

**Comment by rkuhn** [comment]
LGTM

**Comment by ktoso** [comment]
Updated all samples to use File sink/sources and updated the tutorial a little bit as well.

**Pull request merged**
